"""empty message

Revision ID: 1c7092e000d4
Revises: None
Create Date: 2015-12-21 10:19:16.059561

"""

# revision identifiers, used by Alembic.
revision = '1c7092e000d4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_forms')
    op.drop_table('strongs_dict')
    op.drop_table('source_words')
    op.drop_table('simachtani')
    op.drop_table('sourcetext_words')
    op.drop_table('source_texts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_texts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collection', sa.VARCHAR(), nullable=False),
    sa.Column('book', sa.VARCHAR(), nullable=False),
    sa.Column('book_he', sa.VARCHAR(), nullable=True),
    sa.Column('chapter', sa.INTEGER(), nullable=False),
    sa.Column('verse', sa.INTEGER(), nullable=False),
    sa.Column('nikud', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sourcetext_words',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.Column('words_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], [u'source_texts.id'], ),
    sa.ForeignKeyConstraint(['words_id'], [u'source_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simachtani',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nikud', sa.VARCHAR(), nullable=False),
    sa.Column('shoresh', sa.VARCHAR(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_words',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(), nullable=False),
    sa.Column('pos', sa.VARCHAR(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('strongs_num', sa.INTEGER(), nullable=True),
    sa.Column('simachtani_num', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], [u'word_forms.group_id'], ),
    sa.ForeignKeyConstraint(['simachtani_num'], [u'simachtani.id'], ),
    sa.ForeignKeyConstraint(['strongs_num'], [u'strongs_dict.strongs_num'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('strongs_dict',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strongs_num', sa.INTEGER(), nullable=True),
    sa.Column('nikud', sa.VARCHAR(), nullable=False),
    sa.Column('xlit', sa.VARCHAR(), nullable=True),
    sa.Column('pronunciation', sa.VARCHAR(), nullable=True),
    sa.Column('derivation', sa.VARCHAR(), nullable=True),
    sa.Column('strongs_def', sa.VARCHAR(), nullable=True),
    sa.Column('kjv_def', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_forms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('nikud', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
